#!/bin/sh

# Sporočilo, ki se pošlje
message="Commit was made to the repo: $(git log -1 --pretty=%B)"

# Webhook URL za vaš Discord kanal
webhook_url=""

# Pošiljanje sporočila na Discord
curl -H "Content-Type: application/json" \
     -d "{\"content\": \"${message}\"}" \
     $webhook_url
